const translations = {
  tr: {
    nav_home:"Ana Sayfa",nav_about:"Hakkımızda",nav_services:"Hizmetler",nav_projects:"Projeler",nav_blog:"Blog",nav_contact:"İletişim",
    hero_title1:"Geleceği Tasarlıyoruz,",hero_title2:"Kodla Hayata Geçiriyoruz.",
    hero_desc:"WebFlux olarak, işletmenizi dijitalde bir adım öne taşıyacak, en güçlü SEO altyapısına sahip, hızlı ve modern web siteleri tasarlıyoruz.",
    hero_cta1:"Ücretsiz Teklif Al",hero_cta2:"Projelerimizi İncele",
    stats_projects:"Tamamlanan Proje",stats_satisfaction:"Müşteri Memnuniyeti",stats_experience:"Yıllık Deneyim",stats_clients:"Mutlu Müşteri",
    services_title1:"Neler",services_title2:"Yapıyoruz?",
    services_web_title:"Web Tasarım",services_web_desc:"Markanıza özel, kullanıcı dostu ve mobil uyumlu, dönüşüm odaklı tasarımlar.",
    services_eco_title:"E-Ticaret Çözümleri",services_eco_desc:"Satışlarınızı artıracak, hızlı ve güvenli e-ticaret siteleri.",
    services_seo_title:"SEO & Dijital Pazarlama",services_seo_desc:"Google'da ilk sayfada çıkmanız için en güçlü SEO stratejileri.",
    manager_title1:"Vizyonumuz ve",manager_title2:"Hikayemiz",
    manager_p1:"Merhaba, ben WebFlux'un yöneticisi. Yıllardır dijital dünyanın içindeyim ve şunu çok iyi biliyorum: Bir web sitesi sadece kodlardan ibaret değildir; o, markanızın dijital kimliği, vitrininiz ve en önemli satış temsilcinizdir.",
    manager_p2:"WebFlux'u kurarken tek bir amacım vardı: İşletmelerin dijital dünyada hak ettikleri yeri almalarını sağlamak. En güncel teknolojileri, estetik tasarım anlayışıyla birleştirerek, sadece bugün değil gelecekte de başarılı olacak projeler üretiyoruz.",
    manager_p3:"Her projeye kendi işimiz gibi yaklaşıyor, en ince detayına kadar özen gösteriyoruz. Çünkü biliyoruz ki, başarınız bizim başarımızdır.",
    manager_signature:"WebFlux Yöneticisi",
    media_title1:"Projelerimizden",media_title2:"Kareler",
    media_m1_t:"Kodlama Sürecimiz",media_m1_d:"Temiz ve optimize edilmiş kodlar",
    media_m2_t:"Geliştirme Aşaması",media_m2_d:"Modern teknolojilerle kodlama",
    media_m3_t:"Proje Geliştirme",media_m3_d:"Her detay özenle işleniyor",
    media_m4_t:"SEO Çalışmaları",media_m4_d:"Google'da üst sıralara taşıyoruz",
    media_m5_t:"UI/UX Tasarım",media_m5_d:"Kullanıcı odaklı arayüzler",
    media_m6_t:"Proje Sunumu",media_m6_d:"Modern ve etkileyici sunumlar",
    media_m7_t:"Yazılım Geliştirme",media_m7_d:"Performans odaklı kodlar",
    media_m8_t:"Ekip Çalışması",media_m8_d:"Profesyonel ekip koordinasyonu",
    process_title1:"Nasıl",process_title2:"Çalışıyoruz?",
    process_s1_t:"Analiz & Planlama",process_s1_d:"İhtiyaçlarınızı dinliyor, rakiplerinizi analiz ediyor ve size özel bir yol haritası çıkarıyoruz.",
    process_s2_t:"Tasarım (UI/UX)",process_s2_d:"Marka kimliğinize uygun, kullanıcı dostu ve estetik tasarımlar hazırlıyoruz.",
    process_s3_t:"Kodlama & Geliştirme",process_s3_d:"En güncel teknolojilerle, hızlı ve güvenli bir şekilde sitenizi kodluyoruz.",
    process_s4_t:"Test & Yayın",process_s4_d:"Her detayı test ediyor, SEO ayarlarını yapıyor ve sitenizi yayına alıyoruz.",
    testi_title1:"Müşterilerimiz",testi_title2:"Ne Diyor?",
    testi_r1:"WebFlux ile çalışmak harikaydı. Sitemizin hızı ve tasarımı beklentilerimizin çok üzerinde. Satışlarımız %40 arttı!",
    testi_r2:"Kurumsal kimliğimizi en iyi yansıtan siteyi yaptılar. SEO çalışmaları sayesinde Google'da ilk sayfadayız.",
    testi_r3:"E-ticaret sitemiz hızlı ve kullanışlı ama keşke biraz daha hızlı teslim edilseydi. Yine de sonuçtan memnunuz.",
    testi_r4:"İnşaat firmamız için yaptıkları site tam istediğimiz gibi oldu. Referanslarımızı ve projelerimizi en iyi şekilde sergiliyoruz.",
    testi_r5:"Site güzel oldu ancak revizyon süreci biraz uzadı. İletişim daha hızlı olabilirdi. Genel olarak memnunum.",
    testi_r6:"Diş kliniğimiz için online randevu sistemi kurdular. Hasta sayımız 2 katına çıktı. Profesyonel ekip.",
    testi_r7:"Fiyatlar biraz yüksek ama kaliteye değiyor. İşini bilen bir ekip. Tavsiye ederim ama bütçenizi ayarlayın.",
    testi_r8:"Yazılım şirketimiz için modern ve teknik dokümantasyonlu bir site hazırladılar. Demo talepleri ciddi oranda arttı.",
    testi_r9:"Spor salonumuz için üyelik ve ders programı sistemi kurdular. Üye kayıtlarımız online olarak artıyor.",
    testi_r10:"İlk başta iletişimde sıkıntı yaşadık, birkaç kez yazmam gerekti. Ama sonuç güzel oldu. Umarım destek kısmı da güçlenir.",
    testi_r11:"Eğitim platformumuz için harika bir altyapı kurdular. Öğrenci paneli ve ödeme sistemi kusursuz çalışıyor.",
    testi_r12:"Tasarım harika, içerik yönetimi kolay. Sadece mobilde birkaç küçük sorun vardı, hemen düzelttiler. Teşekkürler.",
    review_title1:"Sen de WebFlux'ten",review_title2:"Deneyimini Bizimle Paylaş",
    review_desc:"Hizmetimizden memnun kaldıysanız, deneyiminizi bizimle paylaşın. Yorumunuz, diğer müşterilerimize yol gösterir.",
    review_name:"Adınız Soyadınız *",review_company:"Firma / Web Siteniz",review_email:"E-posta Adresiniz *",
    review_rating:"Puanınız *",review_comment:"Yorumunuz *",review_submit:"Yorumumu Gönder",
    cta_title1:"Projenizi",cta_title2:"Hayata Geçirelim",
    cta_desc:"Fikrinizi bize anlatın, size en uygun çözümü sunalım. Ücretsiz danışmanlık için hemen iletişime geçin.",
    cta_btn:"Hemen Teklif Al",
    footer_desc:"Dijital dünyada markanızı bir adım öne taşıyacak, modern ve SEO uyumlu web siteleri tasarlıyoruz.",
    footer_quick:"Hızlı Linkler",footer_services:"Hizmetlerimiz",footer_contact:"İletişim",
    footer_webdesign:"Web Tasarım",footer_eco:"E-Ticaret",footer_seo:"SEO & Pazarlama",footer_domain:"Domain & Hosting",
    footer_copyright:"Tüm Hakları Saklıdır.",footer_kvkk:"KVKK",footer_sss:"SSS",
    about_title:"Hakkımızda",about_who1:"Biz",about_who2:"Kimiz?",
    about_p1:"WebFlux, dijital dünyada markanızı bir adım öne taşımak için kurulmuş bir web tasarım ve yazılım ajansıdır. Yazılım mühendisleri, tasarımcılar ve dijital pazarlama uzmanlarından oluşan deneyimli ekibimizle, en güncel teknolojileri kullanarak işletmelerin dijital varlıklarını güçlendiriyoruz.",
    about_p2:"Vizyonumuz, Türkiye'den dünyaya açılan projeler üretmek ve müşterilerimize en yüksek dijital getiriyi sağlamaktır. Her projeye bir sanat eseri gibi yaklaşıyor, kodun her satırını özenle yazıyoruz.",
    about_p3:"Modern ofisimizde, birbirinden değerli müşterilerimizin projelerini tutkuyla hayata geçiriyoruz. Çünkü biliyoruz ki, dijital dünyada ilk izlenim her şeydir.",
    about_mission_t:"Misyonumuz",about_mission_d:"İşletmelerin dijital dünyada rekabet edebilmeleri için ihtiyaç duydukları tüm web çözümlerini, en yüksek kalite standartlarında sunmak.",
    about_vision_t:"Vizyonumuz",about_vision_d:"Türkiye'nin önde gelen web tasarım ajanslarından biri olmak ve global ölçekte projeler üretmek.",
    about_values_t:"Değerlerimiz",about_values_d:"Şeffaflık, kalite, müşteri memnuniyeti ve sürekli gelişim. İşimizi tutkuyla yapıyoruz.",
    about_team_t:"Profesyonel Ekip",about_team_d:"Yazılım mühendisleri, UI/UX tasarımcıları, SEO uzmanları ve proje yöneticilerinden oluşan deneyimli kadromuz.",
    about_tech_t:"Modern Teknoloji",about_tech_d:"React, Next.js, Node.js, WordPress, WooCommerce, Laravel gibi en güncel teknolojilerle kodlama.",
    about_support_t:"7/24 Destek",about_support_d:"Projeniz yayına girdikten sonra da yanınızdayız. Bakım, güncelleme ve teknik destek hizmetleri.",
    services_page_title:"Hizmetlerimiz",
    services_page_desc:"Web tasarımından dijital pazarlamaya kadar işletmenizin ihtiyaç duyduğu tüm dijital çözümleri tek çatı altında sunuyoruz.",
    svc1_t:"Kurumsal Web Tasarım",svc1_d:"Markanızı en iyi şekilde yansıtan, hızlı ve SEO uyumlu kurumsal web siteleri tasarlıyoruz.",
    svc2_t:"E-Ticaret Sitesi Kurulumu",svc2_d:"WooCommerce, Shopify, Ticimax ve özel yazılım e-ticaret çözümleri.",
    svc3_t:"SEO Optimizasyonu",svc3_d:"Google'da üst sıralara çıkmanız için teknik SEO, içerik SEO, backlink ve yerel SEO çalışmaları.",
    svc4_t:"Domain ve Hosting",svc4_d:".com, .tr, .net gibi alan adları ve hızlı SSD hosting çözümleri.",
    svc5_t:"Logo ve Kurumsal Kimlik",svc5_d:"Markanıza özel logo tasarımı, kartvizit, antetli kağıt ve kurumsal kimlik kılavuzu.",
    svc6_t:"Mobil Uygulama Geliştirme",svc6_d:"iOS ve Android için native ve cross-platform mobil uygulamalar.",
    svc7_t:"Video ve Animasyon",svc7_d:"Tanıtım videoları, animasyonlu logolar, ürün tanıtım videoları.",
    svc8_t:"Google Ads & Meta Ads",svc8_d:"Google Ads, Facebook Ads ve Instagram Ads reklam yönetimi.",
    svc9_t:"İçerik ve Metin Yazarlığı",svc9_d:"SEO uyumlu blog yazıları, ürün açıklamaları, kurumsal metinler.",
    svc10_t:"Sosyal Medya Yönetimi",svc10_d:"Instagram, Facebook, Twitter, LinkedIn ve TikTok hesap yönetimi.",
    svc11_t:"Web Sitesi Bakım ve Destek",svc11_d:"Sitenizin güncel, güvenli ve hızlı kalması için düzenli bakım hizmetleri.",
    svc12_t:"Hız Optimizasyonu",svc12_d:"Sitenizin yükleme hızını artırıyoruz. Google PageSpeed skorunuzu yükseltiyoruz.",
    svc13_t:"SSL ve Güvenlik",svc13_d:"SSL sertifikası kurulumu, güvenlik duvarı, malware taraması ve güvenlik testleri.",
    svc14_t:"E-posta Pazarlama",svc14_d:"Mailchimp ve benzeri platformlarla e-bülten yönetimi ve müşteri segmentasyonu.",
    svc15_t:"Dijital Pazarlama Danışmanlığı",svc15_d:"İşletmenize özel dijital pazarlama stratejileri. Pazar ve rakip analizi.",
    svc16_t:"Çoklu Dil Desteği",svc16_d:"İşletmenizi global pazara taşıyacak çok dilli web siteleri.",
    svc17_t:"UI/UX Tasarım",svc17_d:"Kullanıcı odaklı arayüz ve deneyim tasarımı. Wireframe, prototip ve testler.",
    svc18_t:"Ürün Fotoğrafçılığı",svc18_d:"E-ticaret ürünleriniz için profesyonel fotoğraf çekimi.",
    projects_page_title:"Referans Projelerimiz",
    projects_page_desc:"Farklı sektörlerden müşterilerimiz için hayata geçirdiğimiz başarılı projelerimizi inceleyin.",
    project_read:"Projeyi İncele →",project_visit:"Siteyi Ziyaret Et",project_details:"Proje Detayları",
    p1_s:"İnşaat & Yapı",p1_t:"MTK Global İnşaat",p1_d:"Kurumsal inşaat firması için referans projeleri ve kurumsal kimliği en iyi yansıtan modern web sitesi.",
    p2_s:"E-Ticaret",p2_t:"TrendyModa.com",p2_d:"Mobil öncelikli, hızlı ve güvenli bir alışveriş deneyimi sunan e-ticaret platformu.",
    p3_s:"Kurumsal / Hukuk",p3_t:"BosphorusHukuk.com",p3_d:"Güven veren kurumsal kimliği ve randevu sistemiyle öne çıkan hukuk bürosu sitesi.",
    p4_s:"Restoran & Kafe",p4_t:"LezzetDurağı.com.tr",p4_d:"Online rezervasyon ve dijital menü özellikleriyle modern bir restoran deneyimi.",
    p5_s:"Portfolyo",p5_t:"MimarAyse.com",p5_d:"Minimalist ve sanatsal tasarımıyla mimari projeleri sergileyen kişisel portfolyo sitesi.",
    p6_s:"E-Ticaret / Teknoloji",p6_t:"TeknoMarketim.com",p6_d:"Gelişmiş filtreleme ve yapay zeka destekli öneri sistemiyle teknoloji ürünleri satış platformu.",
    p7_s:"Sağlık",p7_t:"VitaDentalKlinik.com",p7_d:"Online randevu ve hasta bilgilendirme odaklı, güven veren sağlık sitesi.",
    p8_s:"Eğitim",p8_t:"OnlineAkademi.com",p8_d:"Video dersler ve canlı eğitimlerle interaktif bir online öğrenme platformu.",
    p9_s:"Gayrimenkul",p9_t:"PrimeEmlak.com.tr",p9_d:"Harita üzerinde ilan gösterimi ve gelişmiş arama özellikleriyle emlak platformu.",
    p10_s:"Teknoloji / SaaS",p10_t:"InnovateSoft.com",p10_d:"SaaS ürünleri için modern, dönüşüm odaklı ve teknik dokümantasyon içeren kurumsal site.",
    p11_s:"Spor & Fitness",p11_t:"FitLifeGym.com",p11_d:"Üyelik paketleri, antrenör tanıtımları ve ders programlarıyla dinamik spor salonu sitesi.",
    blog_page_title:"Blog Yazıları",
    blog_read:"Devamını Oku →",
    b1_t:"2024 Web Tasarım Trendleri",b1_d:"Bu yıl öne çıkan 3D öğeler, koyu mod ve mikro animasyonlar hakkında her şey.",
    b2_t:"E-Ticaret Siteniz Neden Yavaş?",b2_d:"Hız, dönüşüm oranını doğrudan etkiler. Sitenizi hızlandırmanın 5 kolay yolu.",
    b3_t:"SEO'da 2024 Algoritma Güncellemeleri",b3_d:"Google'ın son güncellemeleri ışığında sitenizi nasıl optimize etmelisiniz?",
    b4_t:"Mobil Uyumluluk Neden Şart?",b4_d:"Kullanıcıların %70'i mobilden giriyor. Mobil uyumlu olmayan siteler kaybediyor.",
    b5_t:"Doğru Domain Nasıl Seçilir?",b5_d:"Markanız için en uygun alan adını seçmenin püf noktaları ve .com vs .tr farkı.",
    b6_t:"Web Siteniz İçin Bakım Rehberi",b6_d:"Sitenizin güvenliği ve güncelliği için düzenli yapılması gerekenler.",
    contact_title:"Bize Ulaşın",contact_info_t:"İletişim Bilgilerimiz",contact_email_l:"E-posta:",contact_phone_l:"Telefon:",contact_address_l:"Adres:",contact_address:"İstanbul, Türkiye",
    contact_social:"Sosyal medya hesaplarımızdan da bize ulaşabilirsiniz.",
    contact_form_t:"Projenizi Anlatın",contact_name:"Adınız Soyadınız",contact_email:"E-posta Adresiniz",contact_phone:"Telefon Numaranız",
    contact_service:"Hizmet Seçiniz",contact_service_ph:"Bir hizmet seçin",contact_message:"Projeniz Hakkında",contact_message_ph:"Projenizden kısaca bahsedin...",
    contact_submit:"Mesajı Gönder",contact_svc_web:"Web Tasarım",contact_svc_eco:"E-Ticaret",contact_svc_seo:"SEO",contact_svc_mobile:"Mobil Uygulama",contact_svc_logo:"Logo Tasarım",contact_svc_other:"Diğer",
    sss_title:"Sıkça Sorulan Sorular",
    faq1_q:"Web sitem ne kadar sürede hazır olur?",faq1_a:"Projenin kapsamına göre değişmekle birlikte, standart bir kurumsal web sitesi ortalama 7-10 iş günü içerisinde teslim edilir. E-ticaret projeleri ise 15-20 iş günü sürebilmektedir.",
    faq2_q:"SEO çalışması yapıyor musunuz?",faq2_a:"Evet, tüm projelerimiz SEO uyumlu olarak kodlanır. Ayrıca, Google'da üst sıralara çıkmanız için anahtar kelime analizi, içerik optimizasyonu ve teknik SEO hizmetleri sunuyoruz.",
    faq3_q:"Domain ve hosting hizmeti veriyor musunuz?",faq3_a:"Evet, .com, .tr gibi tüm alan adları ve hızlı hosting çözümleri konusunda size destek oluyor, yayına alma sürecini sizin için yönetiyoruz.",
    faq4_q:"Sitem mobil uyumlu olacak mı?",faq4_a:"Kesinlikle. Tüm projelerimiz, eski telefonlar ve bilgisayarlar dahil olmak üzere her cihazda hızlı ve sorunsuz çalışacak şekilde responsive tasarlanır.",
    faq5_q:"Proje sonrası destek veriyor musunuz?",faq5_a:"Evet, teslimattan sonra 1 ay boyunca ücretsiz teknik destek sağlıyoruz. Sonrasında ise bakım anlaşmaları ile sitenizin güncel kalmasını sağlıyoruz.",
    faq6_q:"Ödeme seçenekleri nelerdir?",faq6_a:"Proje başlangıcında %50, teslimatta %50 olacak şekilde ödeme planı sunuyoruz. Havale/EFT ve kredi kartı ile ödeme kabul ediyoruz.",
    faq7_q:"Sitemin içeriğini ben mi sağlayacağım?",faq7_a:"Evet, genellikle içerikleri müşterilerimiz sağlar. Ancak dilerseniz, profesyonel içerik ve metin yazarlığı hizmeti de sunuyoruz.",
    kvkk_title:"KVKK Aydınlatma Metni",
    kvkk_p1:"WebFlux.tr olarak, kişisel verilerinizin güvenliği bizim için en öncelikli konudur. 6698 sayılı Kişisel Verilerin Korunması Kanunu ('KVKK') uyarınca, veri sorumlusu olarak, kişisel verilerinizi aşağıda açıklanan amaçlar doğrultusunda işlemekteyiz.",
    kvkk_h1:"1. Kişisel Verilerin İşlenme Amacı:",kvkk_p2:"Toplanan kişisel verileriniz (ad, soyad, e-posta, telefon), web tasarım ve dijital pazarlama hizmetlerimizi sunmak, taleplerinizi yanıtlamak ve sizinle iletişime geçmek amacıyla işlenmektedir.",
    kvkk_h2:"2. Kişisel Verilerin Aktarılması:",kvkk_p3:"Kişisel verileriniz, yasal yükümlülüklerin yerine getirilmesi amacıyla yetkili kamu kurum ve kuruluşlarına, hizmet aldığımız üçüncü taraf yazılım sağlayıcılarına aktarılabilmektedir.",
    kvkk_h3:"3. Haklarınız:",kvkk_p4:"KVKK'nın 11. maddesi uyarınca; kişisel verilerinizin işlenip işlenmediğini öğrenme, işlenmişse buna ilişkin bilgi talep etme, düzeltilmesini veya silinmesini isteme haklarına sahipsiniz. Taleplerinizi connect.webflux@gmail.com adresine iletebilirsiniz."
  },
  en: {
    nav_home:"Home",nav_about:"About Us",nav_services:"Services",nav_projects:"Projects",nav_blog:"Blog",nav_contact:"Contact",
    hero_title1:"We Design the Future,",hero_title2:"We Bring It to Life with Code.",
    hero_desc:"At WebFlux, we design fast and modern websites with the strongest SEO infrastructure to take your business one step ahead in the digital world.",
    hero_cta1:"Get a Free Quote",hero_cta2:"View Our Projects",
    stats_projects:"Completed Projects",stats_satisfaction:"Client Satisfaction",stats_experience:"Years of Experience",stats_clients:"Happy Clients",
    services_title1:"What",services_title2:"We Do",
    services_web_title:"Web Design",services_web_desc:"Custom, user-friendly and mobile-responsive, conversion-focused designs.",
    services_eco_title:"E-Commerce Solutions",services_eco_desc:"Fast and secure e-commerce websites to increase your sales.",
    services_seo_title:"SEO & Digital Marketing",services_seo_desc:"The strongest SEO strategies to rank on Google's first page.",
    manager_title1:"Our Vision and",manager_title2:"Story",
    manager_p1:"Hello, I'm the manager of WebFlux. I've been in the digital world for years and I know this very well: A website is not just code; it's your brand's digital identity, your showcase and your most important sales representative.",
    manager_p2:"When I founded WebFlux, I had one goal: To help businesses take the place they deserve in the digital world.",
    manager_p3:"We approach every project as if it were our own, paying attention to the finest details.",
    manager_signature:"WebFlux Manager",
    media_title1:"Frames from",media_title2:"Our Projects",
    media_m1_t:"Our Coding Process",media_m1_d:"Clean and optimized code",
    media_m2_t:"Development Phase",media_m2_d:"Coding with modern technologies",
    media_m3_t:"Project Development",media_m3_d:"Every detail is carefully handled",
    media_m4_t:"SEO Work",media_m4_d:"We push you to the top of Google",
    media_m5_t:"UI/UX Design",media_m5_d:"User-focused interfaces",
    media_m6_t:"Project Presentation",media_m6_d:"Modern and impressive presentations",
    media_m7_t:"Software Development",media_m7_d:"Performance-focused code",
    media_m8_t:"Team Work",media_m8_d:"Professional team coordination",
    process_title1:"How We",process_title2:"Work",
    process_s1_t:"Analysis & Planning",process_s1_d:"We listen to your needs, analyze your competitors and create a custom roadmap.",
    process_s2_t:"Design (UI/UX)",process_s2_d:"We prepare user-friendly and aesthetic designs that match your brand.",
    process_s3_t:"Coding & Development",process_s3_d:"We code your site quickly and securely using the latest technologies.",
    process_s4_t:"Test & Launch",process_s4_d:"We test every detail, set up SEO and launch your website.",
    testi_title1:"What Our Clients",testi_title2:"Say",
    testi_r1:"Working with WebFlux was amazing. The speed and design of our site exceeded our expectations. Our sales increased by 40%!",
    testi_r2:"They built the site that best reflects our corporate identity. Thanks to their SEO work, we are on Google's first page.",
    testi_r3:"Our e-commerce site is fast and useful but I wish it had been delivered faster.",
    testi_r4:"The site they made for our construction company turned out exactly how we wanted.",
    testi_r5:"The site turned out well but the revision process took a bit long. Overall I'm satisfied.",
    testi_r6:"They set up an online appointment system for our dental clinic. Our patient count doubled.",
    testi_r7:"Prices are a bit high but worth the quality. A team that knows its job.",
    testi_r8:"They prepared a modern, technically documented site for our software company.",
    testi_r9:"They set up a membership system for our gym. Our member registrations are increasing online.",
    testi_r10:"We had some communication issues at first. But the result was good.",
    testi_r11:"They built a great infrastructure for our education platform. Everything works flawlessly.",
    testi_r12:"The design is great, content management is easy. They fixed small issues immediately.",
    review_title1:"Share Your",review_title2:"Experience with WebFlux",
    review_desc:"If you were satisfied with our service, share your experience with us.",
    review_name:"Your Full Name *",review_company:"Company / Website",review_email:"Your Email Address *",
    review_rating:"Your Rating *",review_comment:"Your Review *",review_submit:"Submit My Review",
    cta_title1:"Let's Bring Your",cta_title2:"Project to Life",
    cta_desc:"Tell us your idea, and we'll offer you the best solution. Contact us now for a free consultation.",
    cta_btn:"Get a Quote Now",
    footer_desc:"We design modern and SEO-friendly websites that will take your brand one step ahead in the digital world.",
    footer_quick:"Quick Links",footer_services:"Our Services",footer_contact:"Contact",
    footer_webdesign:"Web Design",footer_eco:"E-Commerce",footer_seo:"SEO & Marketing",footer_domain:"Domain & Hosting",
    footer_copyright:"All Rights Reserved.",footer_kvkk:"Privacy",footer_sss:"FAQ",
    about_title:"About Us",about_who1:"Who",about_who2:"We Are?",
    about_p1:"WebFlux is a web design and software agency founded to take your brand one step ahead in the digital world. With our experienced team of software engineers, designers and digital marketing experts, we strengthen the digital assets of businesses using the latest technologies.",
    about_p2:"Our vision is to produce projects that open from Turkey to the world and to provide our clients with the highest digital return.",
    about_p3:"In our modern office, we passionately bring our valuable clients' projects to life.",
    about_mission_t:"Our Mission",about_mission_d:"To deliver all web solutions businesses need to compete in the digital world at the highest quality standards.",
    about_vision_t:"Our Vision",about_vision_d:"To become one of Turkey's leading web design agencies and produce projects on a global scale.",
    about_values_t:"Our Values",about_values_d:"Transparency, quality, customer satisfaction and continuous improvement.",
    about_team_t:"Professional Team",about_team_d:"Our experienced team of software engineers, UI/UX designers, SEO experts and project managers.",
    about_tech_t:"Modern Technology",about_tech_d:"Coding with the latest technologies such as React, Next.js, Node.js, WordPress, WooCommerce, Laravel.",
    about_support_t:"24/7 Support",about_support_d:"We're with you after launch. Maintenance, updates and technical support services.",
    services_page_title:"Our Services",
    services_page_desc:"From web design to digital marketing, we offer all the digital solutions your business needs under one roof.",
    svc1_t:"Corporate Web Design",svc1_d:"We design fast and SEO-friendly corporate websites that reflect your brand best.",
    svc2_t:"E-Commerce Setup",svc2_d:"WooCommerce, Shopify, Ticimax and custom e-commerce solutions.",
    svc3_t:"SEO Optimization",svc3_d:"Technical SEO, content SEO, backlink and local SEO to rank higher on Google.",
    svc4_t:"Domain and Hosting",svc4_d:".com, .tr, .net domains and fast SSD hosting solutions.",
    svc5_t:"Logo and Corporate Identity",svc5_d:"Custom logo design, business cards, letterhead and corporate identity guide.",
    svc6_t:"Mobile App Development",svc6_d:"Native and cross-platform mobile apps for iOS and Android.",
    svc7_t:"Video and Animation",svc7_d:"Promotional videos, animated logos, product demo videos.",
    svc8_t:"Google Ads & Meta Ads",svc8_d:"Google Ads, Facebook Ads and Instagram Ads management.",
    svc9_t:"Content and Copywriting",svc9_d:"SEO-friendly blog posts, product descriptions, corporate texts.",
    svc10_t:"Social Media Management",svc10_d:"Instagram, Facebook, Twitter, LinkedIn and TikTok account management.",
    svc11_t:"Website Maintenance & Support",svc11_d:"Regular maintenance to keep your site up-to-date, secure and fast.",
    svc12_t:"Speed Optimization",svc12_d:"We increase your site's loading speed and improve Google PageSpeed score.",
    svc13_t:"SSL and Security",svc13_d:"SSL certificate installation, firewall, malware scan and security tests.",
    svc14_t:"Email Marketing",svc14_d:"Newsletter management and customer segmentation via Mailchimp and similar platforms.",
    svc15_t:"Digital Marketing Consulting",svc15_d:"Custom digital marketing strategies. Market and competitor analysis.",
    svc16_t:"Multi-Language Support",svc16_d:"Multilingual websites to take your business to the global market.",
    svc17_t:"UI/UX Design",svc17_d:"User-focused interface and experience design. Wireframes, prototypes and tests.",
    svc18_t:"Product Photography",svc18_d:"Professional photography for your e-commerce products.",
    projects_page_title:"Our Reference Projects",
    projects_page_desc:"Explore our successful projects we've delivered for clients from various sectors.",
    project_read:"View Project →",project_visit:"Visit Website",project_details:"Project Details",
    p1_s:"Construction",p1_t:"MTK Global Construction",p1_d:"Modern website that best reflects reference projects and corporate identity for a corporate construction firm.",
    p2_s:"E-Commerce",p2_t:"TrendyModa.com",p2_d:"E-commerce platform offering a mobile-first, fast and secure shopping experience.",
    p3_s:"Corporate / Law",p3_t:"BosphorusLaw.com",p3_d:"Law firm website with trust-inspiring corporate identity and appointment system.",
    p4_s:"Restaurant & Cafe",p4_t:"LezzetDurağı.com.tr",p4_d:"Modern restaurant experience with online reservation and digital menu features.",
    p5_s:"Portfolio",p5_t:"ArchitectAyse.com",p5_d:"Personal portfolio site showcasing architectural projects with minimalist design.",
    p6_s:"E-Commerce / Tech",p6_t:"TeknoMarketim.com",p6_d:"Tech product sales platform with advanced filtering and AI-powered recommendation system.",
    p7_s:"Healthcare",p7_t:"VitaDentalClinic.com",p7_d:"Trustworthy health site focused on online appointments and patient information.",
    p8_s:"Education",p8_t:"OnlineAcademy.com",p8_d:"Interactive online learning platform with video lessons and live training.",
    p9_s:"Real Estate",p9_t:"PrimeRealEstate.com",p9_d:"Real estate platform with map-based listing display and advanced search.",
    p10_s:"Tech / SaaS",p10_t:"InnovateSoft.com",p10_d:"Modern, conversion-focused corporate site with technical documentation for SaaS products.",
    p11_s:"Sports & Fitness",p11_t:"FitLifeGym.com",p11_d:"Dynamic gym website with membership packages, trainer profiles and class schedules.",
    blog_page_title:"Blog Posts",blog_read:"Read More →",
    b1_t:"2024 Web Design Trends",b1_d:"Everything about 3D elements, dark mode and micro-animations trending this year.",
    b2_t:"Why Is Your E-Commerce Site Slow?",b2_d:"Speed directly affects conversion rate. 5 easy ways to speed up your site.",
    b3_t:"2024 SEO Algorithm Updates",b3_d:"How should you optimize your site in light of Google's latest updates?",
    b4_t:"Why Is Mobile Compatibility Essential?",b4_d:"70% of users visit from mobile. Sites that aren't mobile-friendly lose.",
    b5_t:"How to Choose the Right Domain?",b5_d:"Tips for choosing the best domain for your brand and .com vs .tr differences.",
    b6_t:"Website Maintenance Guide",b6_d:"Things to do regularly for your site's security and up-to-dateness.",
    contact_title:"Contact Us",contact_info_t:"Contact Information",contact_email_l:"Email:",contact_phone_l:"Phone:",contact_address_l:"Address:",contact_address:"Istanbul, Turkey",
    contact_social:"You can also reach us via our social media accounts.",
    contact_form_t:"Tell Us About Your Project",contact_name:"Your Full Name",contact_email:"Your Email",contact_phone:"Your Phone Number",
    contact_service:"Select a Service",contact_service_ph:"Select a service",contact_message:"About Your Project",contact_message_ph:"Tell us briefly about your project...",
    contact_submit:"Send Message",contact_svc_web:"Web Design",contact_svc_eco:"E-Commerce",contact_svc_seo:"SEO",contact_svc_mobile:"Mobile App",contact_svc_logo:"Logo Design",contact_svc_other:"Other",
    sss_title:"Frequently Asked Questions",
    faq1_q:"How long does it take to build my website?",faq1_a:"Depending on the scope, a standard corporate website is delivered in 7-10 business days. E-commerce projects may take 15-20 business days.",
    faq2_q:"Do you do SEO work?",faq2_a:"Yes, all our projects are coded SEO-friendly. We also provide keyword analysis, content optimization and technical SEO services.",
    faq3_q:"Do you provide domain and hosting?",faq3_a:"Yes, we support you with all domains like .com, .tr and fast hosting solutions, and we manage the launch process for you.",
    faq4_q:"Will my site be mobile-responsive?",faq4_a:"Absolutely. All our projects are designed to work fast and flawlessly on every device, including older phones and computers.",
    faq5_q:"Do you provide post-project support?",faq5_a:"Yes, we provide free technical support for 1 month after delivery. Afterwards, we keep your site updated with maintenance agreements.",
    faq6_q:"What are the payment options?",faq6_a:"We offer a payment plan of 50% at project start and 50% on delivery. We accept bank transfer and credit card.",
    faq7_q:"Will I provide the content of my site?",faq7_a:"Yes, usually our clients provide the content. However, we also offer professional content and copywriting services if you wish.",
    kvkk_title:"Privacy Policy (KVKK)",
    kvkk_p1:"As WebFlux.tr, the security of your personal data is our top priority. In accordance with the Personal Data Protection Law No. 6698 ('KVKK'), as data controller, we process your personal data for the purposes described below.",
    kvkk_h1:"1. Purpose of Processing Personal Data:",kvkk_p2:"Your collected personal data (name, surname, email, phone) is processed to provide our web design and digital marketing services, respond to your requests and contact you.",
    kvkk_h2:"2. Transfer of Personal Data:",kvkk_p3:"Your personal data may be transferred to authorized public institutions and third-party software providers we work with (hosting, email services) to fulfill legal obligations.",
    kvkk_h3:"3. Your Rights:",kvkk_p4:"Under Article 11 of KVKK, you have the right to learn whether your personal data is processed, request information if processed, and request correction or deletion. You can send your requests to connect.webflux@gmail.com."
  },
  fa: {
    nav_home:"خانه",nav_about:"درباره ما",nav_services:"خدمات",nav_projects:"پروژه‌ها",nav_blog:"وبلاگ",nav_contact:"تماس",
    hero_title1:"ما آینده را طراحی می‌کنیم،",hero_title2:"آن را با کد زنده می‌کنیم.",
    hero_desc:"در WebFlux، ما وب‌سایت‌های سریع و مدرن با قوی‌ترین زیرساخت سئو طراحی می‌کنیم تا کسب‌وکار شما را در دنیای دیجیتال یک قدم جلوتر ببریم.",
    hero_cta1:"دریافت مشاوره رایگان",hero_cta2:"مشاهده پروژه‌ها",
    stats_projects:"پروژه تکمیل شده",stats_satisfaction:"رضایت مشتری",stats_experience:"سال تجربه",stats_clients:"مشتری راضی",
    services_title1:"چه کارهایی",services_title2:"انجام می‌دهیم؟",
    services_web_title:"طراحی وب",services_web_desc:"طراحی اختصاصی، کاربرپسند و سازگار با موبایل.",
    services_eco_title:"راهکارهای تجارت الکترونیک",services_eco_desc:"وب‌سایت‌های سریع و امن فروشگاهی برای افزایش فروش شما.",
    services_seo_title:"سئو و بازاریابی دیجیتال",services_seo_desc:"قوی‌ترین استراتژی‌های سئو برای رتبه در صفحه اول گوگل.",
    manager_title1:"چشم‌انداز و",manager_title2:"داستان ما",
    manager_p1:"سلام، من مدیر WebFlux هستم. سال‌ها در دنیای دیجیتال بوده‌ام و این را خوب می‌دانم: یک وب‌سایت فقط کد نیست؛ هویت دیجیتال برند شماست.",
    manager_p2:"وقتی WebFlux را تأسیس کردم، یک هدف داشتم: کمک به کسب‌وکارها برای گرفتن جایگاه شایسته خود در دنیای دیجیتال.",
    manager_p3:"به هر پروژه مانند کار خودمان نزدیک می‌شویم و به کوچک‌ترین جزئیات توجه می‌کنیم.",
    manager_signature:"مدیر WebFlux",
    media_title1:"قاب‌هایی از",media_title2:"پروژه‌های ما",
    media_m1_t:"فرآیند کدنویسی ما",media_m1_d:"کدهای تمیز و بهینه",
    media_m2_t:"مرحله توسعه",media_m2_d:"کدنویسی با فناوری‌های مدرن",
    media_m3_t:"توسعه پروژه",media_m3_d:"هر جزئیات با دقت پردازش می‌شود",
    media_m4_t:"کارهای سئو",media_m4_d:"شما را به بالای گوگل می‌رسانیم",
    media_m5_t:"طراحی UI/UX",media_m5_d:"رابط‌های کاربرمحور",
    media_m6_t:"ارائه پروژه",media_m6_d:"ارائه‌های مدرن و تأثیرگذار",
    media_m7_t:"توسعه نرم‌افزار",media_m7_d:"کدهای عملکردمحور",
    media_m8_t:"کار تیمی",media_m8_d:"هماهنگی حرفه‌ای تیم",
    process_title1:"چگونه",process_title2:"کار می‌کنیم؟",
    process_s1_t:"تحلیل و برنامه‌ریزی",process_s1_d:"به نیازهای شما گوش می‌دهیم و نقشه راه اختصاصی تهیه می‌کنیم.",
    process_s2_t:"طراحی (UI/UX)",process_s2_d:"طرح‌های کاربرپسند و زیبا متناسب با برند شما آماده می‌کنیم.",
    process_s3_t:"کدنویسی و توسعه",process_s3_d:"با جدیدترین فناوری‌ها، سایت شما را سریع و امن کدنویسی می‌کنیم.",
    process_s4_t:"تست و انتشار",process_s4_d:"هر جزئیات را تست می‌کنیم و سایت شما را منتشر می‌کنیم.",
    testi_title1:"مشتریان ما",testi_title2:"چه می‌گویند؟",
    testi_r1:"کار با WebFlux عالی بود. فروش ما ۴۰٪ افزایش یافت!",
    testi_r2:"سایتی ساختند که بهترین بازتاب هویت شرکتی ماست.",
    testi_r3:"سایت فروشگاهی ما سریع و کاربردی است اما کاش سریع‌تر تحویل داده می‌شد.",
    testi_r4:"سایتی که برای شرکت ساختمانی ما ساختند دقیقاً همان چیزی بود که می‌خواستیم.",
    testi_r5:"سایت خوب شد اما روند بازبینی کمی طولانی شد. در کل راضی هستم.",
    testi_r6:"برای کلینیک دندانپزشکی ما سیستم نوبت‌دهی آنلاین راه‌اندازی کردند.",
    testi_r7:"قیمت‌ها کمی بالاست اما ارزش کیفیت را دارد.",
    testi_r8:"برای شرکت نرم‌افزاری ما یک سایت مدرن آماده کردند.",
    testi_r9:"برای باشگاه ورزشی ما سیستم عضویت راه‌اندازی کردند.",
    testi_r10:"ابتدا در ارتباط مشکل داشتیم اما نتیجه خوب شد.",
    testi_r11:"برای پلتفرم آموزشی ما زیرساخت عالی ساختند.",
    testi_r12:"طراحی عالی است، مدیریت محتوا آسان است.",
    review_title1:"تجربه خود را با",review_title2:"WebFlux به اشتراک بگذارید",
    review_desc:"اگر از خدمات ما راضی بودید، تجربه خود را با ما به اشتراک بگذارید.",
    review_name:"نام و نام خانوادگی *",review_company:"شرکت / وب‌سایت شما",review_email:"آدرس ایمیل شما *",
    review_rating:"امتیاز شما *",review_comment:"نظر شما *",review_submit:"ارسال نظر",
    cta_title1:"بیایید پروژه شما را",cta_title2:"زنده کنیم",
    cta_desc:"ایده خود را به ما بگویید، بهترین راه‌حل را ارائه می‌دهیم.",
    cta_btn:"دریافت قیمت",
    footer_desc:"ما وب‌سایت‌های مدرن و سئوپسند طراحی می‌کنیم که برند شما را یک قدم جلوتر می‌برد.",
    footer_quick:"لینک‌های سریع",footer_services:"خدمات ما",footer_contact:"تماس",
    footer_webdesign:"طراحی وب",footer_eco:"تجارت الکترونیک",footer_seo:"سئو و بازاریابی",footer_domain:"دامنه و هاست",
    footer_copyright:"تمامی حقوق محفوظ است.",footer_kvkk:"حریم خصوصی",footer_sss:"سوالات متداول",
    about_title:"درباره ما",about_who1:"ما",about_who2:"کی هستیم؟",
    about_p1:"WebFlux یک آژانس طراحی وب و نرم‌افزار است که برای بردن برند شما یک قدم جلوتر در دنیای دیجیتال تأسیس شده است.",
    about_p2:"چشم‌انداز ما تولید پروژه‌هایی است که از ترکیه به جهان باز می‌شوند.",
    about_p3:"در دفتر مدرن خود، پروژه‌های مشتریان ارزشمندمان را با اشتیاق زنده می‌کنیم.",
    about_mission_t:"مأموریت ما",about_mission_d:"ارائه تمام راه‌حل‌های وب که کسب‌وکارها برای رقابت در دنیای دیجیتال نیاز دارند.",
    about_vision_t:"چشم‌انداز ما",about_vision_d:"تبدیل شدن به یکی از آژانس‌های پیشرو طراحی وب ترکیه و تولید پروژه در مقیاس جهانی.",
    about_values_t:"ارزش‌های ما",about_values_d:"شفافیت، کیفیت، رضایت مشتری و بهبود مستمر.",
    about_team_t:"تیم حرفه‌ای",about_team_d:"تیم مجرب ما از مهندسان نرم‌افزار، طراحان UI/UX و متخصصان سئو.",
    about_tech_t:"فناوری مدرن",about_tech_d:"کدنویسی با جدیدترین فناوری‌ها مانند React، Next.js، Node.js، WordPress.",
    about_support_t:"پشتیبانی ۲۴/۷",about_support_d:"ما بعد از انتشار هم با شما هستیم. نگهداری، به‌روزرسانی و پشتیبانی فنی.",
    services_page_title:"خدمات ما",
    services_page_desc:"از طراحی وب تا بازاریابی دیجیتال، تمام راه‌حل‌های دیجیتال مورد نیاز کسب‌وکار شما را زیر یک سقف ارائه می‌دهیم.",
    svc1_t:"طراحی وب شرکتی",svc1_d:"ما وب‌سایت‌های شرکتی سریع و سئوپسند طراحی می‌کنیم.",
    svc2_t:"راه‌اندازی فروشگاه اینترنتی",svc2_d:"راه‌حل‌های WooCommerce، Shopify، Ticimax و سفارشی.",
    svc3_t:"بهینه‌سازی سئو",svc3_d:"سئو فنی، سئو محتوا، بک‌لینک و سئوی محلی.",
    svc4_t:"دامنه و هاست",svc4_d:"دامنه‌های .com، .tr، .net و راه‌حل‌های هاست SSD سریع.",
    svc5_t:"لوگو و هویت شرکتی",svc5_d:"طراحی لوگوی سفارشی، کارت ویزیت و راهنمای هویت شرکتی.",
    svc6_t:"توسعه اپلیکیشن موبایل",svc6_d:"اپلیکیشن‌های native و cross-platform برای iOS و Android.",
    svc7_t:"ویدیو و انیمیشن",svc7_d:"ویدیوهای تبلیغاتی، لوگوهای متحرک، ویدیوهای معرفی محصول.",
    svc8_t:"Google Ads و Meta Ads",svc8_d:"مدیریت تبلیغات Google Ads، Facebook Ads و Instagram Ads.",
    svc9_t:"محتوا و نویسندگی",svc9_d:"پست‌های وبلاگ سئوپسند، توضیحات محصول، متون شرکتی.",
    svc10_t:"مدیریت شبکه‌های اجتماعی",svc10_d:"مدیریت حساب‌های Instagram، Facebook، Twitter، LinkedIn و TikTok.",
    svc11_t:"نگهداری و پشتیبانی وب‌سایت",svc11_d:"نگهداری منظم برای به‌روز، امن و سریع نگه داشتن سایت شما.",
    svc12_t:"بهینه‌سازی سرعت",svc12_d:"سرعت بارگذاری سایت شما را افزایش می‌دهیم و امتیاز PageSpeed را بهبود می‌بخشیم.",
    svc13_t:"SSL و امنیت",svc13_d:"نصب گواهی SSL، فایروال، اسکن بدافزار و تست‌های امنیتی.",
    svc14_t:"بازاریابی ایمیلی",svc14_d:"مدیریت خبرنامه و بخش‌بندی مشتریان از طریق Mailchimp و پلتفرم‌های مشابه.",
    svc15_t:"مشاوره بازاریابی دیجیتال",svc15_d:"استراتژی‌های بازاریابی دیجیتال سفارشی. تحلیل بازار و رقبا.",
    svc16_t:"پشتیبانی چندزبانه",svc16_d:"وب‌سایت‌های چندزبانه برای بردن کسب‌وکار شما به بازار جهانی.",
    svc17_t:"طراحی UI/UX",svc17_d:"طراحی رابط و تجربه کاربرمحور. Wireframe، نمونه اولیه و تست‌ها.",
    svc18_t:"عکاسی محصول",svc18_d:"عکاسی حرفه‌ای برای محصولات فروشگاهی شما.",
    projects_page_title:"پروژه‌های مرجع ما",
    projects_page_desc:"پروژه‌های موفق ما که برای مشتریان از بخش‌های مختلف ارائه کرده‌ایم را کاوش کنید.",
    project_read:"مشاهده پروژه →",project_visit:"مشاهده وب‌سایت",project_details:"جزئیات پروژه",
    p1_s:"ساختمان",p1_t:"MTK Global Construction",p1_d:"وب‌سایت مدرن که بهترین بازتاب پروژه‌های مرجع و هویت شرکتی یک شرکت ساختمانی است.",
    p2_s:"تجارت الکترونیک",p2_t:"TrendyModa.com",p2_d:"پلتفرم فروشگاهی با تجربه خرید سریع و امن.",
    p3_s:"شرکتی / حقوقی",p3_t:"BosphorusLaw.com",p3_d:"وب‌سایت دفتر وکالت با هویت شرکتی قابل اعتماد و سیستم نوبت‌دهی.",
    p4_s:"رستوران و کافه",p4_t:"LezzetDurağı.com.tr",p4_d:"تجربه رستوران مدرن با رزرو آنلاین و منوی دیجیتال.",
    p5_s:"نمونه کار",p5_t:"ArchitectAyse.com",p5_d:"سایت نمونه کار شخصی با طراحی مینیمال برای نمایش پروژه‌های معماری.",
    p6_s:"تجارت الکترونیک / فناوری",p6_t:"TeknoMarketim.com",p6_d:"پلتفرم فروش محصولات فناوری با فیلتر پیشرفته و سیستم توصیه هوشمند.",
    p7_s:"بهداشت و درمان",p7_t:"VitaDentalClinic.com",p7_d:"سایت سلامت قابل اعتماد با تمرکز بر نوبت‌دهی آنلاین و اطلاعات بیمار.",
    p8_s:"آموزش",p8_t:"OnlineAcademy.com",p8_d:"پلتفرم یادگیری آنلاین تعاملی با درس‌های ویدیویی و آموزش زنده.",
    p9_s:"املاک",p9_t:"PrimeRealEstate.com",p9_d:"پلتفرم املاک با نمایش آگهی روی نقشه و جستجوی پیشرفته.",
    p10_s:"فناوری / SaaS",p10_t:"InnovateSoft.com",p10_d:"سایت شرکتی مدرن با مستندات فنی برای محصولات SaaS.",
    p11_s:"ورزش و تناسب اندام",p11_t:"FitLifeGym.com",p11_d:"وب‌سایت پویا باشگاه ورزشی با بسته‌های عضویت، پروفایل مربیان و برنامه کلاس.",
    blog_page_title:"پست‌های وبلاگ",blog_read:"ادامه مطلب →",
    b1_t:"روندهای طراحی وب ۲۰۲۴",b1_d:"همه چیز درباره عناصر سه‌بعدی، حالت تاریک و میکرو انیمیشن‌ها.",
    b2_t:"چرا سایت فروشگاهی شما کند است؟",b2_d:"سرعت مستقیماً بر نرخ تبدیل تأثیر می‌گذارد. ۵ راه آسان برای تسریع سایت.",
    b3_t:"به‌روزرسانی‌های الگوریتم سئو ۲۰۲۴",b3_d:"چگونه سایت خود را با آخرین به‌روزرسانی‌های گوگل بهینه کنید؟",
    b4_t:"چرا سازگاری با موبایل ضروری است؟",b4_d:"۷۰٪ کاربران از موبایل بازدید می‌کنند. سایت‌های ناسازگار ضرر می‌کنند.",
    b5_t:"چگونه دامنه مناسب را انتخاب کنیم؟",b5_d:"نکات انتخاب بهترین دامنه برای برند شما و تفاوت .com و .tr.",
    b6_t:"راهنمای نگهداری وب‌سایت",b6_d:"کارهایی که باید به طور منظم برای امنیت و به‌روز بودن سایت انجام دهید.",
    contact_title:"تماس با ما",contact_info_t:"اطلاعات تماس",contact_email_l:"ایمیل:",contact_phone_l:"تلفن:",contact_address_l:"آدرس:",contact_address:"استانبول، ترکیه",
    contact_social:"می‌توانید از طریق حساب‌های شبکه‌های اجتماعی ما نیز با ما تماس بگیرید.",
    contact_form_t:"پروژه خود را به ما بگویید",contact_name:"نام و نام خانوادگی",contact_email:"ایمیل شما",contact_phone:"شماره تلفن شما",
    contact_service:"یک خدمت انتخاب کنید",contact_service_ph:"یک خدمت انتخاب کنید",contact_message:"درباره پروژه شما",contact_message_ph:"به طور خلاصه درباره پروژه خود بگویید...",
    contact_submit:"ارسال پیام",contact_svc_web:"طراحی وب",contact_svc_eco:"تجارت الکترونیک",contact_svc_seo:"سئو",contact_svc_mobile:"اپلیکیشن موبایل",contact_svc_logo:"طراحی لوگو",contact_svc_other:"سایر",
    sss_title:"سوالات متداول",
    faq1_q:"ساخت وب‌سایت من چقدر طول می‌کشد؟",faq1_a:"بسته به دامنه پروژه، یک وب‌سایت شرکتی استاندارد در ۷ تا ۱۰ روز کاری تحویل داده می‌شود. پروژه‌های فروشگاهی ۱۵ تا ۲۰ روز کاری طول می‌کشد.",
    faq2_q:"آیا کار سئو انجام می‌دهید؟",faq2_a:"بله، تمام پروژه‌های ما سئوپسند کدنویسی می‌شوند. همچنین خدمات تحلیل کلمات کلیدی، بهینه‌سازی محتوا و سئوی فنی ارائه می‌دهیم.",
    faq3_q:"آیا دامنه و هاست ارائه می‌دهید؟",faq3_a:"بله، ما در تمام دامنه‌های .com، .tr و راه‌حل‌های هاست سریع از شما پشتیبانی می‌کنیم و فرآیند انتشار را برای شما مدیریت می‌کنیم.",
    faq4_q:"آیا سایت من سازگار با موبایل خواهد بود؟",faq4_a:"قطعاً. تمام پروژه‌های ما به گونه‌ای طراحی شده‌اند که در هر دستگاهی، از جمله تلفن‌ها و کامپیوترهای قدیمی، سریع و بی‌نقص کار کنند.",
    faq5_q:"آیا پشتیبانی پس از پروژه ارائه می‌دهید؟",faq5_a:"بله، ما ۱ ماه پس از تحویل پشتیبانی فنی رایگان ارائه می‌دهیم. پس از آن، با توافق نگهداری سایت شما را به‌روز نگه می‌داریم.",
    faq6_q:"گزینه‌های پرداخت چیست؟",faq6_a:"ما طرح پرداخت ۵۰٪ در شروع پروژه و ۵۰٪ در تحویل ارائه می‌دهیم. حواله بانکی و کارت اعتباری می‌پذیریم.",
    faq7_q:"آیا محتوای سایتم را خودم تأمین می‌کنم؟",faq7_a:"بله، معمولاً مشتریان ما محتوا را تأمین می‌کنند. اما در صورت تمایل، خدمات محتوا و نویسندگی حرفه‌ای نیز ارائه می‌دهیم.",
    kvkk_title:"سیاست حفظ حریم خصوصی",
    kvkk_p1:"به عنوان WebFlux.tr، امنیت داده‌های شخصی شما اولویت اصلی ماست. مطابق قانون حفاظت از داده‌های شخصی شماره ۶۶۹۸، به عنوان کنترل‌کننده داده، داده‌های شخصی شما را برای اهداف توصیف شده در زیر پردازش می‌کنیم.",
    kvkk_h1:"۱. هدف پردازش داده‌های شخصی:",kvkk_p2:"داده‌های شخصی جمع‌آوری شده شما (نام، نام خانوادگی، ایمیل، تلفن) برای ارائه خدمات طراحی وب و بازاریابی دیجیتال، پاسخ به درخواست‌ها و تماس با شما پردازش می‌شود.",
    kvkk_h2:"۲. انتقال داده‌های شخصی:",kvkk_p3:"داده‌های شخصی شما ممکن است برای انجام تعهدات قانونی به نهادهای عمومی مجاز و ارائه‌دهندگان نرم‌افزار شخص ثالث (هاست، خدمات ایمیل) منتقل شود.",
    kvkk_h3:"۳. حقوق شما:",kvkk_p4:"طبق ماده ۱۱ قانون، شما حق دارید بدانید آیا داده‌های شخصی شما پردازش می‌شود، درخواست اطلاعات کنید و اصلاح یا حذف را درخواست کنید. درخواست‌های خود را به connect.webflux@gmail.com ارسال کنید."
  },
  ar: {
    nav_home:"الرئيسية",nav_about:"من نحن",nav_services:"خدماتنا",nav_projects:"المشاريع",nav_blog:"المدونة",nav_contact:"اتصل بنا",
    hero_title1:"نصمم المستقبل،",hero_title2:"ونحوّله إلى واقع بالكود.",
    hero_desc:"في WebFlux، نصمم مواقع سريعة وعصرية بأقوى بنية SEO لنأخذ عملك خطوة إلى الأمام في العالم الرقمي.",
    hero_cta1:"احصل على عرض مجاني",hero_cta2:"شاهد مشاريعنا",
    stats_projects:"مشروع مكتمل",stats_satisfaction:"رضا العملاء",stats_experience:"سنوات خبرة",stats_clients:"عميل سعيد",
    services_title1:"ماذا",services_title2:"نفعل؟",
    services_web_title:"تصميم المواقع",services_web_desc:"تصاميم مخصصة وسهلة الاستخدام ومتوافقة مع الجوال.",
    services_eco_title:"حلول التجارة الإلكترونية",services_eco_desc:"مواقع تجارة إلكترونية سريعة وآمنة لزيادة مبيعاتك.",
    services_seo_title:"SEO والتسويق الرقمي",services_seo_desc:"أقوى استراتيجيات SEO للظهور في الصفحة الأولى من Google.",
    manager_title1:"رؤيتنا",manager_title2:"وقصتنا",
    manager_p1:"مرحباً، أنا مدير WebFlux. كنت في العالم الرقمي لسنوات وأعرف هذا جيداً: الموقع ليس مجرد كود؛ إنه هوية علامتك التجارية الرقمية.",
    manager_p2:"عندما أسست WebFlux، كان لدي هدف واحد: مساعدة الشركات على أخذ المكان الذي تستحقه في العالم الرقمي.",
    manager_p3:"نتعامل مع كل مشروع كما لو كان مشروعنا، ونولي اهتماماً لأدق التفاصيل.",
    manager_signature:"مدير WebFlux",
    media_title1:"لقطات من",media_title2:"مشاريعنا",
    media_m1_t:"عملية البرمجة لدينا",media_m1_d:"أكواد نظيفة ومحسّنة",
    media_m2_t:"مرحلة التطوير",media_m2_d:"البرمجة بأحدث التقنيات",
    media_m3_t:"تطوير المشروع",media_m3_d:"كل تفصيل يُعالج بعناية",
    media_m4_t:"أعمال SEO",media_m4_d:"نرفعك إلى قمة Google",
    media_m5_t:"تصميم UI/UX",media_m5_d:"واجهات تركز على المستخدم",
    media_m6_t:"عرض المشروع",media_m6_d:"عروض عصرية ومؤثرة",
    media_m7_t:"تطوير البرمجيات",media_m7_d:"أكواد تركز على الأداء",
    media_m8_t:"العمل الجماعي",media_m8_d:"تنسيق احترافي للفريق",
    process_title1:"كيف",process_title2:"نعمل؟",
    process_s1_t:"التحليل والتخطيط",process_s1_d:"نستمع لاحتياجاتك ونعد لك خارطة طريق مخصصة.",
    process_s2_t:"التصميم (UI/UX)",process_s2_d:"نعد تصاميم سهلة الاستخدام وجمالية تتناسب مع هوية علامتك.",
    process_s3_t:"البرمجة والتطوير",process_s3_d:"نبرمج موقعك بسرعة وأمان باستخدام أحدث التقنيات.",
    process_s4_t:"الاختبار والإطلاق",process_s4_d:"نختبر كل تفصيل ونطلق موقعك.",
    testi_title1:"ماذا يقول",testi_title2:"عملاؤنا؟",
    testi_r1:"كان العمل مع WebFlux رائعاً. زادت مبيعاتنا بنسبة 40%!",
    testi_r2:"بنوا الموقع الذي يعكس هويتنا المؤسسية بأفضل شكل.",
    testi_r3:"موقع التجارة الإلكترونية سريع ومفيد لكن كنت أتمنى لو تم التسليم بشكل أسرع.",
    testi_r4:"الموقع الذي صنعوه لشركة البناء لدينا جاء بالضبط كما أردنا.",
    testi_r5:"الموقع جاء جيداً لكن عملية المراجعة استغرقت وقتاً طويلاً. بشكل عام أنا راضٍ.",
    testi_r6:"أقاموا نظام حجز مواعيد عبر الإنترنت لعيادة الأسنان لدينا.",
    testi_r7:"الأسعار مرتفعة قليلاً لكنها تستحق الجودة.",
    testi_r8:"أعدوا موقعاً عصرياً لشركة البرمجيات لدينا.",
    testi_r9:"أقاموا نظام عضوية لصالة الرياضة لدينا.",
    testi_r10:"واجهنا مشاكل في التواصل في البداية لكن النتيجة كانت جيدة.",
    testi_r11:"بنوا بنية تحتية رائعة لمنصتنا التعليمية.",
    testi_r12:"التصميم رائع، إدارة المحتوى سهلة.",
    review_title1:"شارك تجربتك",review_title2:"مع WebFlux",
    review_desc:"إذا كنت راضياً عن خدمتنا، شارك تجربتك معنا.",
    review_name:"اسمك الكامل *",review_company:"الشركة / موقعك",review_email:"بريدك الإلكتروني *",
    review_rating:"تقييمك *",review_comment:"رأيك *",review_submit:"إرسال رأيي",
    cta_title1:"لنحوّل مشروعك",cta_title2:"إلى حقيقة",
    cta_desc:"أخبرنا بفكرتك، وسنقدم لك أفضل حل.",
    cta_btn:"احصل على عرض",
    footer_desc:"نصمم مواقع عصرية وصديقة لـ SEO ستأخذ علامتك التجارية خطوة إلى الأمام.",
    footer_quick:"روابط سريعة",footer_services:"خدماتنا",footer_contact:"اتصل بنا",
    footer_webdesign:"تصميم المواقع",footer_eco:"التجارة الإلكترونية",footer_seo:"SEO والتسويق",footer_domain:"النطاق والاستضافة",
    footer_copyright:"جميع الحقوق محفوظة.",footer_kvkk:"الخصوصية",footer_sss:"الأسئلة الشائعة",
    about_title:"من نحن",about_who1:"من",about_who2:"نحن؟",
    about_p1:"WebFlux هي وكالة تصميم وتطوير ويب تأسست لأخذ علامتك التجارية خطوة إلى الأمام في العالم الرقمي.",
    about_p2:"رؤيتنا هي إنتاج مشاريع تنطلق من تركيا إلى العالم.",
    about_p3:"في مكتبنا الحديث، نحيي مشاريع عملائنا الثمينين بشغف.",
    about_mission_t:"مهمتنا",about_mission_d:"تقديم جميع حلول الويب التي تحتاجها الشركات للتنافس في العالم الرقمي.",
    about_vision_t:"رؤيتنا",about_vision_d:"أن نصبح واحدة من وكالات تصميم الويب الرائدة في تركيا.",
    about_values_t:"قيمنا",about_values_d:"الشفافية والجودة ورضا العملاء والتحسين المستمر.",
    about_team_t:"فريق احترافي",about_team_d:"فريقنا من مهندسي البرمجيات ومصممي UI/UX وخبراء SEO.",
    about_tech_t:"تقنية حديثة",about_tech_d:"البرمجة بأحدث التقنيات مثل React و Next.js و Node.js.",
    about_support_t:"دعم 24/7",about_support_d:"نحن معك بعد الإطلاق. خدمات الصيانة والتحديث والدعم الفني.",
    services_page_title:"خدماتنا",
    services_page_desc:"من تصميم الويب إلى التسويق الرقمي، نقدم جميع الحلول الرقمية التي يحتاجها عملك تحت سقف واحد.",
    svc1_t:"تصميم مواقع الشركات",svc1_d:"نصمم مواقع شركات سريعة وصديقة لـ SEO تعكس علامتك بأفضل شكل.",
    svc2_t:"إنشاء متجر إلكتروني",svc2_d:"حلول WooCommerce و Shopify و Ticimax والمخصصة.",
    svc3_t:"تحسين SEO",svc3_d:"SEO التقني و SEO المحتوى والروابط الخلفية و SEO المحلي.",
    svc4_t:"النطاق والاستضافة",svc4_d:"نطاقات .com و .tr و .net وحلول استضافة SSD سريعة.",
    svc5_t:"الشعار والهوية المؤسسية",svc5_d:"تصميم شعار مخصص وبطاقات العمل ودليل الهوية المؤسسية.",
    svc6_t:"تطوير تطبيقات الجوال",svc6_d:"تطبيقات iOS و Android الأصلية والمتعددة المنصات.",
    svc7_t:"الفيديو والرسوم المتحركة",svc7_d:"فيديوهات ترويجية وشعارات متحركة وفيديوهات عرض المنتجات.",
    svc8_t:"Google Ads و Meta Ads",svc8_d:"إدارة إعلانات Google و Facebook و Instagram.",
    svc9_t:"المحتوى وكتابة النصوص",svc9_d:"مقالات مدونة صديقة لـ SEO ووصف المنتجات والنصوص المؤسسية.",
    svc10_t:"إدارة وسائل التواصل",svc10_d:"إدارة حسابات Instagram و Facebook و Twitter و LinkedIn و TikTok.",
    svc11_t:"صيانة ودعم الموقع",svc11_d:"صيانة منتظمة لإبقاء موقعك محدثاً وآمناً وسريعاً.",
    svc12_t:"تحسين السرعة",svc12_d:"نزيد سرعة تحميل موقعك ونحسن نتيجة PageSpeed.",
    svc13_t:"SSL والأمان",svc13_d:"تركيب شهادة SSL والجدار الناري وفحص البرمجيات الخبيثة.",
    svc14_t:"التسويق بالبريد الإلكتروني",svc14_d:"إدارة النشرات الإخبارية وتقسيم العملاء عبر Mailchimp.",
    svc15_t:"استشارات التسويق الرقمي",svc15_d:"استراتيجيات تسويق رقمي مخصصة. تحليل السوق والمنافسين.",
    svc16_t:"دعم متعدد اللغات",svc16_d:"مواقع متعددة اللغات لنقل عملك إلى السوق العالمية.",
    svc17_t:"تصميم UI/UX",svc17_d:"تصميم واجهة وتجربة تركز على المستخدم.",
    svc18_t:"تصوير المنتجات",svc18_d:"تصوير احترافي لمنتجات التجارة الإلكترونية.",
    projects_page_title:"مشاريعنا المرجعية",
    projects_page_desc:"استكشف مشاريعنا الناجحة التي قدمناها لعملاء من قطاعات مختلفة.",
    project_read:"عرض المشروع →",project_visit:"زيارة الموقع",project_details:"تفاصيل المشروع",
    p1_s:"البناء والتشييد",p1_t:"MTK Global Construction",p1_d:"موقع حديث يعكس أفضل مشاريع مرجعية وهوية مؤسسية لشركة بناء.",
    p2_s:"التجارة الإلكترونية",p2_t:"TrendyModa.com",p2_d:"منصة تجارة إلكترونية تقدم تجربة تسوق سريعة وآمنة.",
    p3_s:"مؤسسي / قانوني",p3_t:"BosphorusLaw.com",p3_d:"موقع مكتب محاماة بهوية مؤسسية موثوقة ونظام مواعيد.",
    p4_s:"مطعم ومقهى",p4_t:"LezzetDurağı.com.tr",p4_d:"تجربة مطعم عصرية مع حجز عبر الإنترنت وقائمة رقمية.",
    p5_s:"معرض أعمال",p5_t:"ArchitectAyse.com",p5_d:"موقع معرض أعمال شخصي بتصميم بسيط لعرض المشاريع المعمارية.",
    p6_s:"التجارة الإلكترونية / التقنية",p6_t:"TeknoMarketim.com",p6_d:"منصة بيع منتجات تقنية مع تصفية متقدمة ونظام توصية ذكي.",
    p7_s:"الرعاية الصحية",p7_t:"VitaDentalClinic.com",p7_d:"موقع صحي موثوق يركز على المواعيد عبر الإنترنت ومعلومات المريض.",
    p8_s:"التعليم",p8_t:"OnlineAcademy.com",p8_d:"منصة تعلم تفاعلية عبر الإنترنت بدروس فيديو وتدريب مباشر.",
    p9_s:"العقارات",p9_t:"PrimeRealEstate.com",p9_d:"منصة عقارية مع عرض القوائم على الخريطة والبحث المتقدم.",
    p10_s:"التقنية / SaaS",p10_t:"InnovateSoft.com",p10_d:"موقع مؤسسي حديث يركز على التحويل مع توثيق تقني لمنتجات SaaS.",
    p11_s:"الرياضة واللياقة",p11_t:"FitLifeGym.com",p11_d:"موقع صالة رياضية ديناميكي مع باقات العضوية وملفات المدربين.",
    blog_page_title:"مقالات المدونة",blog_read:"اقرأ المزيد →",
    b1_t:"اتجاهات تصميم الويب 2024",b1_d:"كل شيء عن العناصر ثلاثية الأبعاد والوضع الداكن والرسوم المتحركة الدقيقة.",
    b2_t:"لماذا موقع التجارة الإلكترونية بطيء؟",b2_d:"السرعة تؤثر مباشرة على معدل التحويل. 5 طرق سهلة لتسريع موقعك.",
    b3_t:"تحديثات خوارزمية SEO 2024",b3_d:"كيف يجب أن تحسّن موقعك في ضوء تحديثات Google الأخيرة؟",
    b4_t:"لماذا التوافق مع الجوال ضروري؟",b4_d:"70% من المستخدمين يزورون من الجوال. المواقع غير المتوافقة تخسر.",
    b5_t:"كيف تختار النطاق المناسب؟",b5_d:"نصائح لاختيار أفضل نطاق لعلامتك والفرق بين .com و .tr.",
    b6_t:"دليل صيانة الموقع",b6_d:"الأشياء التي يجب القيام بها بانتظام لأمان موقعك وحداثته.",
    contact_title:"اتصل بنا",contact_info_t:"معلومات الاتصال",contact_email_l:"البريد:",contact_phone_l:"الهاتف:",contact_address_l:"العنوان:",contact_address:"اسطنبول، تركيا",
    contact_social:"يمكنك أيضاً التواصل معنا عبر حسابات التواصل الاجتماعي.",
    contact_form_t:"أخبرنا عن مشروعك",contact_name:"اسمك الكامل",contact_email:"بريدك الإلكتروني",contact_phone:"رقم هاتفك",
    contact_service:"اختر خدمة",contact_service_ph:"اختر خدمة",contact_message:"عن مشروعك",contact_message_ph:"أخبرنا بإيجاز عن مشروعك...",
    contact_submit:"إرسال الرسالة",contact_svc_web:"تصميم المواقع",contact_svc_eco:"التجارة الإلكترونية",contact_svc_seo:"SEO",contact_svc_mobile:"تطبيق جوال",contact_svc_logo:"تصميم شعار",contact_svc_other:"أخرى",
    sss_title:"الأسئلة الشائعة",
    faq1_q:"كم يستغرق بناء موقعي؟",faq1_a:"حسب نطاق المشروع، يتم تسليم موقع مؤسسي قياسي في 7-10 أيام عمل. مشاريع التجارة الإلكترونية قد تستغرق 15-20 يوم عمل.",
    faq2_q:"هل تقومون بأعمال SEO؟",faq2_a:"نعم، جميع مشاريعنا مبرمجة صديقة لـ SEO. نقدم أيضاً خدمات تحليل الكلمات المفتاحية وتحسين المحتوى و SEO التقني.",
    faq3_q:"هل تقدمون النطاق والاستضافة؟",faq3_a:"نعم، ندعمك في جميع النطاقات مثل .com و .tr وحلول الاستضافة السريعة، وندير عملية الإطلاق نيابة عنك.",
    faq4_q:"هل سيكون موقعي متوافقاً مع الجوال؟",faq4_a:"بالتأكيد. جميع مشاريعنا مصممة للعمل بسرعة وبشكل مثالي على كل جهاز، بما في ذلك الهواتف والحواسيب القديمة.",
    faq5_q:"هل تقدمون دعماً بعد المشروع؟",faq5_a:"نعم، نقدم دعماً تقنياً مجانياً لمدة شهر بعد التسليم. بعد ذلك، نحافظ على تحديث موقعك باتفاقيات الصيانة.",
    faq6_q:"ما هي خيارات الدفع؟",faq6_a:"نقدم خطة دفع 50% في بداية المشروع و 50% عند التسليم. نقبل التحويل البنكي وبطاقة الائتمان.",
    faq7_q:"هل سأوفر محتوى موقعي؟",faq7_a:"نعم، عادة يقدم عملاؤنا المحتوى. ومع ذلك، نقدم أيضاً خدمات المحتوى وكتابة النصوص الاحترافية إذا أردت.",
    kvkk_title:"سياسة الخصوصية",
    kvkk_p1:"بصفتنا WebFlux.tr، أمن بياناتك الشخصية هو أولويتنا القصوى. وفقاً لقانون حماية البيانات الشخصية رقم 6698، كمراقب بيانات، نعالج بياناتك الشخصية للأغراض الموضحة أدناه.",
    kvkk_h1:"1. الغرض من معالجة البيانات الشخصية:",kvkk_p2:"تتم معالجة بياناتك الشخصية المجمعة (الاسم واللقب والبريد الإلكتروني والهاتف) لتقديم خدمات تصميم الويب والتسويق الرقمي والرد على طلباتك والتواصل معك.",
    kvkk_h2:"2. نقل البيانات الشخصية:",kvkk_p3:"قد يتم نقل بياناتك الشخصية إلى المؤسسات العامة المصرح لها ومقدمي البرامج من الأطراف الثالثة (الاستضافة وخدمات البريد الإلكتروني) للوفاء بالالتزامات القانونية.",
    kvkk_h3:"3. حقوقك:",kvkk_p4:"بموجب المادة 11 من القانون، لديك الحق في معرفة ما إذا كانت بياناتك الشخصية معالجة وطلب المعلومات وطلب التصحيح أو الحذف. يمكنك إرسال طلباتك إلى connect.webflux@gmail.com."
  },
  ru: {
    nav_home:"Главная",nav_about:"О нас",nav_services:"Услуги",nav_projects:"Проекты",nav_blog:"Блог",nav_contact:"Контакты",
    hero_title1:"Мы проектируем будущее,",hero_title2:"Оживляем его кодом.",
    hero_desc:"В WebFlux мы создаём быстрые и современные сайты с сильнейшей SEO-инфраструктурой, чтобы вывести ваш бизнес на шаг вперёд.",
    hero_cta1:"Получить бесплатную консультацию",hero_cta2:"Посмотреть проекты",
    stats_projects:"Завершённых проектов",stats_satisfaction:"Довольных клиентов",stats_experience:"Лет опыта",stats_clients:"Счастливых клиентов",
    services_title1:"Что",services_title2:"мы делаем?",
    services_web_title:"Веб-дизайн",services_web_desc:"Индивидуальный, удобный и адаптивный дизайн, ориентированный на конверсию.",
    services_eco_title:"Решения для e-commerce",services_eco_desc:"Быстрые и безопасные интернет-магазины для увеличения продаж.",
    services_seo_title:"SEO и цифровой маркетинг",services_seo_desc:"Сильнейшие SEO-стратегии для попадания на первую страницу Google.",
    manager_title1:"Наше видение",manager_title2:"и история",
    manager_p1:"Здравствуйте, я руководитель WebFlux. Я много лет в цифровом мире и знаю: сайт — это не просто код; это цифровая идентичность вашего бренда.",
    manager_p2:"Когда я основал WebFlux, у меня была одна цель: помочь бизнесу занять достойное место в цифровом мире.",
    manager_p3:"Мы подходим к каждому проекту как к своему, уделяя внимание мельчайшим деталям.",
    manager_signature:"Руководитель WebFlux",
    media_title1:"Кадры из",media_title2:"наших проектов",
    media_m1_t:"Наш процесс программирования",media_m1_d:"Чистый и оптимизированный код",
    media_m2_t:"Этап разработки",media_m2_d:"Кодирование с современными технологиями",
    media_m3_t:"Разработка проекта",media_m3_d:"Каждая деталь обрабатывается тщательно",
    media_m4_t:"Работа по SEO",media_m4_d:"Мы выводим вас в топ Google",
    media_m5_t:"UI/UX дизайн",media_m5_d:"Интерфейсы, ориентированные на пользователя",
    media_m6_t:"Презентация проекта",media_m6_d:"Современные презентации",
    media_m7_t:"Разработка ПО",media_m7_d:"Код, ориентированный на производительность",
    media_m8_t:"Командная работа",media_m8_d:"Профессиональная координация команды",
    process_title1:"Как мы",process_title2:"работаем?",
    process_s1_t:"Анализ и планирование",process_s1_d:"Мы слушаем ваши потребности и создаём индивидуальную дорожную карту.",
    process_s2_t:"Дизайн (UI/UX)",process_s2_d:"Мы готовим удобные дизайны, соответствующие идентичности вашего бренда.",
    process_s3_t:"Кодирование и разработка",process_s3_d:"Мы быстро и безопасно программируем ваш сайт.",
    process_s4_t:"Тестирование и запуск",process_s4_d:"Мы тестируем каждую деталь и запускаем ваш сайт.",
    testi_title1:"Что говорят",testi_title2:"наши клиенты?",
    testi_r1:"Работа с WebFlux была потрясающей. Продажи выросли на 40%!",
    testi_r2:"Они создали сайт, который лучше всего отражает нашу идентичность.",
    testi_r3:"Наш интернет-магазин быстрый и удобный, но хотелось бы, чтобы его сдали быстрее.",
    testi_r4:"Сайт для нашей строительной компании оказался именно таким, как мы хотели.",
    testi_r5:"Сайт получился хорошим, но процесс доработки затянулся. В целом я доволен.",
    testi_r6:"Они установили систему онлайн-записи для нашей стоматологии.",
    testi_r7:"Цены немного высокие, но качество того стоит.",
    testi_r8:"Они подготовили современный сайт для нашей IT-компании.",
    testi_r9:"Они установили систему членства для нашего спортзала.",
    testi_r10:"Сначала были проблемы с общением, но результат хороший.",
    testi_r11:"Они построили отличную инфраструктуру для нашей образовательной платформы.",
    testi_r12:"Дизайн отличный, управление контентом простое.",
    review_title1:"Поделитесь своим опытом",review_title2:"с WebFlux",
    review_desc:"Если вы остались довольны нашим сервисом, поделитесь своим опытом.",
    review_name:"Ваше имя и фамилия *",review_company:"Компания / Сайт",review_email:"Ваш email *",
    review_rating:"Ваша оценка *",review_comment:"Ваш отзыв *",review_submit:"Отправить отзыв",
    cta_title1:"Давайте воплотим",cta_title2:"ваш проект в жизнь",
    cta_desc:"Расскажите нам свою идею, и мы предложим лучшее решение.",
    cta_btn:"Получить предложение",
    footer_desc:"Мы создаём современные и SEO-дружественные сайты, которые выведут ваш бренд вперёд.",
    footer_quick:"Быстрые ссылки",footer_services:"Наши услуги",footer_contact:"Контакты",
    footer_webdesign:"Веб-дизайн",footer_eco:"Электронная коммерция",footer_seo:"SEO и маркетинг",footer_domain:"Домен и хостинг",
    footer_copyright:"Все права защищены.",footer_kvkk:"Конфиденциальность",footer_sss:"Вопросы",
    about_title:"О нас",about_who1:"Кто",about_who2:"мы?",
    about_p1:"WebFlux — это агентство веб-дизайна и разработки, основанное, чтобы вывести ваш бренд на шаг вперёд в цифровом мире.",
    about_p2:"Наше видение — создавать проекты, которые открывают Турцию миру.",
    about_p3:"В нашем современном офисе мы с энтузиазмом реализуем проекты наших ценных клиентов.",
    about_mission_t:"Наша миссия",about_mission_d:"Предоставлять все веб-решения, необходимые бизнесу для конкуренции в цифровом мире.",
    about_vision_t:"Наше видение",about_vision_d:"Стать одним из ведущих агентств веб-дизайна Турции и создавать проекты в глобальном масштабе.",
    about_values_t:"Наши ценности",about_values_d:"Прозрачность, качество, удовлетворённость клиентов и постоянное совершенствование.",
    about_team_t:"Профессиональная команда",about_team_d:"Наша команда из инженеров-программистов, UI/UX дизайнеров и SEO-специалистов.",
    about_tech_t:"Современные технологии",about_tech_d:"Кодирование на новейших технологиях, таких как React, Next.js, Node.js, WordPress.",
    about_support_t:"Поддержка 24/7",about_support_d:"Мы с вами после запуска. Обслуживание, обновления и техническая поддержка.",
    services_page_title:"Наши услуги",
    services_page_desc:"От веб-дизайна до цифрового маркетинга — все цифровые решения для вашего бизнеса под одной крышей.",
    svc1_t:"Корпоративный веб-дизайн",svc1_d:"Мы создаём быстрые и SEO-дружественные корпоративные сайты.",
    svc2_t:"Создание интернет-магазина",svc2_d:"Решения WooCommerce, Shopify, Ticimax и индивидуальные.",
    svc3_t:"SEO-оптимизация",svc3_d:"Техническое SEO, SEO контента, бэклинки и локальное SEO.",
    svc4_t:"Домен и хостинг",svc4_d:"Домены .com, .tr, .net и быстрые SSD-хостинги.",
    svc5_t:"Логотип и корпоративная идентичность",svc5_d:"Индивидуальный дизайн логотипа, визитки, фирменный стиль.",
    svc6_t:"Разработка мобильных приложений",svc6_d:"Нативные и кросс-платформенные приложения для iOS и Android.",
    svc7_t:"Видео и анимация",svc7_d:"Промо-ролики, анимированные логотипы, видео о продуктах.",
    svc8_t:"Google Ads и Meta Ads",svc8_d:"Управление рекламой Google, Facebook и Instagram.",
    svc9_t:"Контент и копирайтинг",svc9_d:"SEO-статьи для блога, описания продуктов, корпоративные тексты.",
    svc10_t:"Управление соцсетями",svc10_d:"Управление аккаунтами Instagram, Facebook, Twitter, LinkedIn, TikTok.",
    svc11_t:"Обслуживание и поддержка сайта",svc11_d:"Регулярное обслуживание для актуальности, безопасности и скорости сайта.",
    svc12_t:"Оптимизация скорости",svc12_d:"Мы повышаем скорость загрузки сайта и улучшаем оценку PageSpeed.",
    svc13_t:"SSL и безопасность",svc13_d:"Установка SSL, файрвол, сканирование на вирусы, тесты безопасности.",
    svc14_t:"Email-маркетинг",svc14_d:"Управление рассылками и сегментация клиентов через Mailchimp.",
    svc15_t:"Консалтинг по цифровому маркетингу",svc15_d:"Индивидуальные стратегии цифрового маркетинга. Анализ рынка и конкурентов.",
    svc16_t:"Многоязычная поддержка",svc16_d:"Многоязычные сайты для вывода вашего бизнеса на мировой рынок.",
    svc17_t:"UI/UX дизайн",svc17_d:"Дизайн интерфейсов и опыта, ориентированный на пользователя.",
    svc18_t:"Фотосъёмка продуктов",svc18_d:"Профессиональная съёмка товаров для e-commerce.",
    projects_page_title:"Наши референсные проекты",
    projects_page_desc:"Изучите наши успешные проекты, реализованные для клиентов из разных отраслей.",
    project_read:"Смотреть проект →",project_visit:"Посетить сайт",project_details:"Детали проекта",
    p1_s:"Строительство",p1_t:"MTK Global Construction",p1_d:"Современный сайт, отражающий проекты и корпоративную идентичность строительной компании.",
    p2_s:"E-commerce",p2_t:"TrendyModa.com",p2_d:"Платформа электронной коммерции с быстрым и безопасным опытом покупок.",
    p3_s:"Корпоративный / Юридический",p3_t:"BosphorusLaw.com",p3_d:"Сайт юридической фирмы с надёжной идентичностью и системой записи.",
    p4_s:"Ресторан и кафе",p4_t:"LezzetDurağı.com.tr",p4_d:"Современный опыт ресторана с онлайн-бронированием и цифровым меню.",
    p5_s:"Портфолио",p5_t:"ArchitectAyse.com",p5_d:"Личный сайт-портфолио с минималистичным дизайном для архитектурных проектов.",
    p6_s:"E-commerce / Технологии",p6_t:"TeknoMarketim.com",p6_d:"Платформа продаж техники с продвинутой фильтрацией и умными рекомендациями.",
    p7_s:"Здравоохранение",p7_t:"VitaDentalClinic.com",p7_d:"Надёжный медицинский сайт с онлайн-записью и информацией для пациентов.",
    p8_s:"Образование",p8_t:"OnlineAcademy.com",p8_d:"Интерактивная платформа онлайн-обучения с видеоуроками и живыми занятиями.",
    p9_s:"Недвижимость",p9_t:"PrimeRealEstate.com",p9_d:"Платформа недвижимости с отображением объявлений на карте и продвинутым поиском.",
    p10_s:"Технологии / SaaS",p10_t:"InnovateSoft.com",p10_d:"Современный корпоративный сайт с технической документацией для SaaS.",
    p11_s:"Спорт и фитнес",p11_t:"FitLifeGym.com",p11_d:"Динамичный сайт спортзала с абонементами, профилями тренеров и расписанием.",
    blog_page_title:"Статьи блога",blog_read:"Читать далее →",
    b1_t:"Тренды веб-дизайна 2024",b1_d:"Всё о 3D-элементах, тёмном режиме и микроанимациях.",
    b2_t:"Почему ваш интернет-магазин медленный?",b2_d:"Скорость напрямую влияет на конверсию. 5 простых способов ускорить сайт.",
    b3_t:"Обновления алгоритма SEO 2024",b3_d:"Как оптимизировать сайт с учётом последних обновлений Google?",
    b4_t:"Почему важна мобильная адаптация?",b4_d:"70% пользователей заходят с мобильных. Неадаптированные сайты теряют.",
    b5_t:"Как выбрать правильный домен?",b5_d:"Советы по выбору лучшего домена для вашего бренда и разница между .com и .tr.",
    b6_t:"Руководство по обслуживанию сайта",b6_d:"Что нужно делать регулярно для безопасности и актуальности вашего сайта.",
    contact_title:"Свяжитесь с нами",contact_info_t:"Контактная информация",contact_email_l:"Email:",contact_phone_l:"Телефон:",contact_address_l:"Адрес:",contact_address:"Стамбул, Турция",
    contact_social:"Вы также можете связаться с нами через наши соцсети.",
    contact_form_t:"Расскажите о вашем проекте",contact_name:"Ваше имя и фамилия",contact_email:"Ваш email",contact_phone:"Ваш номер телефона",
    contact_service:"Выберите услугу",contact_service_ph:"Выберите услугу",contact_message:"О вашем проекте",contact_message_ph:"Расскажите кратко о вашем проекте...",
    contact_submit:"Отправить сообщение",contact_svc_web:"Веб-дизайн",contact_svc_eco:"Электронная коммерция",contact_svc_seo:"SEO",contact_svc_mobile:"Мобильное приложение",contact_svc_logo:"Дизайн логотипа",contact_svc_other:"Другое",
    sss_title:"Часто задаваемые вопросы",
    faq1_q:"Сколько времени займёт создание моего сайта?",faq1_a:"В зависимости от объёма проекта, стандартный корпоративный сайт сдаётся за 7-10 рабочих дней. Проекты интернет-магазинов могут занимать 15-20 рабочих дней.",
    faq2_q:"Вы делаете SEO?",faq2_a:"Да, все наши проекты кодируются с учётом SEO. Мы также предоставляем анализ ключевых слов, оптимизацию контента и технический SEO.",
    faq3_q:"Вы предоставляете домен и хостинг?",faq3_a:"Да, мы поддерживаем вас со всеми доменами, такими как .com, .tr, и быстрыми хостингами, и управляем процессом запуска за вас.",
    faq4_q:"Будет ли мой сайт адаптивным?",faq4_a:"Обязательно. Все наши проекты разрабатываются для быстрой и безупречной работы на любом устройстве, включая старые телефоны и компьютеры.",
    faq5_q:"Вы предоставляете поддержку после проекта?",faq5_a:"Да, мы предоставляем бесплатную техническую поддержку в течение 1 месяца после сдачи. Затем мы поддерживаем актуальность вашего сайта по договорам обслуживания.",
    faq6_q:"Какие варианты оплаты?",faq6_a:"Мы предлагаем план оплаты 50% в начале проекта и 50% при сдаче. Принимаем банковский перевод и кредитную карту.",
    faq7_q:"Я буду предоставлять контент своего сайта?",faq7_a:"Да, обычно контент предоставляют наши клиенты. Однако, если хотите, мы также предлагаем услуги профессионального контента и копирайтинга.",
    kvkk_title:"Политика конфиденциальности",
    kvkk_p1:"Как WebFlux.tr, мы ставим безопасность ваших персональных данных на первое место. В соответствии с Законом о защите персональных данных № 6698, как контролёр данных, мы обрабатываем ваши персональные данные для целей, описанных ниже.",
    kvkk_h1:"1. Цель обработки персональных данных:",kvkk_p2:"Ваши собранные персональные данные (имя, фамилия, email, телефон) обрабатываются для предоставления услуг веб-дизайна и цифрового маркетинга, ответа на ваши запросы и связи с вами.",
    kvkk_h2:"2. Передача персональных данных:",kvkk_p3:"Ваши персональные данные могут быть переданы уполномоченным государственным учреждениям и сторонним поставщикам программного обеспечения (хостинг, email-сервисы) для выполнения юридических обязательств.",
    kvkk_h3:"3. Ваши права:",kvkk_p4:"Согласно статье 11 Закона, вы имеете право узнать, обрабатываются ли ваши персональные данные, запросить информацию, а также запросить исправление или удаление. Отправляйте запросы на connect.webflux@gmail.com."
  }
};

const langMeta = { tr:{flag:"TR",dir:"ltr"}, en:{flag:"EN",dir:"ltr"}, fa:{flag:"FA",dir:"rtl"}, ar:{flag:"AR",dir:"rtl"}, ru:{flag:"RU",dir:"ltr"} };

function setLanguage(lang) {
  if(!translations[lang]) lang = 'tr';
  localStorage.setItem('webflux_lang', lang);
  document.documentElement.lang = lang;
  document.documentElement.dir = langMeta[lang].dir;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if(translations[lang][key]) {
      if(el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') el.placeholder = translations[lang][key];
      else el.textContent = translations[lang][key];
    }
  });
  document.querySelectorAll('[data-i18n-ph]').forEach(el => {
    const key = el.getAttribute('data-i18n-ph');
    if(translations[lang][key]) el.placeholder = translations[lang][key];
  });
  const lbl = document.getElementById('currentLangLabel');
  if(lbl) lbl.textContent = langMeta[lang].flag;
  document.querySelectorAll('.lang-option').forEach(o => o.classList.toggle('active', o.dataset.lang === lang));
}

document.addEventListener('DOMContentLoaded', () => {
  setLanguage(localStorage.getItem('webflux_lang') || 'tr');
  const t = document.getElementById('langToggle'), d = document.getElementById('langDropdown');
  if(t && d) {
    t.addEventListener('click', e => { e.stopPropagation(); d.classList.toggle('active'); });
    document.addEventListener('click', () => d.classList.remove('active'));
    document.querySelectorAll('.lang-option').forEach(o => o.addEventListener('click', () => {
      setLanguage(o.dataset.lang);
      d.classList.remove('active');
    }));
  }
});